default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "1.1.0"
    hooks:
      - id: sync_with_poetry

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.3.2"
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        args:
          - "--recursive"
          - "--aggregate=vuln"
          - "--configfile=pyproject.toml"
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args:
          - "--fix"

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: src/fight/example
        exclude_types:
          - markdown
      - id: check-added-large-files
        args:
          - "--maxkb=1024"
      - id: check-yaml
        exclude: \.gitlab-ci.yml
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        args:
          - "--config-file=pyproject.toml"
          - "--install-types"
          - "--non-interactive"
        exclude: "alembic/"
        additional_dependencies:
          - astroid==2.15.6 ; python_version >= "3.11" and python_version < "4.0"
          - autoflake==2.2.1 ; python_version >= "3.11" and python_version < "4.0"
          - bandit==1.7.5 ; python_version >= "3.11" and python_version < "4.0"
          - black==23.7.0 ; python_version >= "3.11" and python_version < "4.0"
          - certifi==2023.7.22 ; python_version >= "3.11" and python_version < "4.0"
          - cfgv==3.4.0 ; python_version >= "3.11" and python_version < "4.0"
          - charset-normalizer==3.2.0 ; python_version >= "3.11" and python_version < "4.0"
          - click==8.1.7 ; python_version >= "3.11" and python_version < "4.0"
          - colorama==0.4.6 ; python_version >= "3.11" and python_version < "4.0" and (sys_platform == "win32" or platform_system == "Windows")
          - coverage==7.3.0 ; python_version >= "3.11" and python_version < "4.0"
          - dill==0.3.7 ; python_version >= "3.11" and python_version < "4.0"
          - distlib==0.3.7 ; python_version >= "3.11" and python_version < "4.0"
          - dparse==0.6.3 ; python_version >= "3.11" and python_version < "4.0"
          - filelock==3.12.3 ; python_version >= "3.11" and python_version < "4.0"
          - flake8-polyfill==1.0.2 ; python_version >= "3.11" and python_version < "4.0"
          - flake8==6.1.0 ; python_version >= "3.11" and python_version < "4.0"
          - gitdb==4.0.10 ; python_version >= "3.11" and python_version < "4.0"
          - gitpython==3.1.33 ; python_version >= "3.11" and python_version < "4.0"
          - identify==2.5.27 ; python_version >= "3.11" and python_version < "4.0"
          - idna==3.4 ; python_version >= "3.11" and python_version < "4.0"
          - iniconfig==2.0.0 ; python_version >= "3.11" and python_version < "4.0"
          - isort==5.12.0 ; python_version >= "3.11" and python_version < "4.0"
          - jinja2==3.1.2 ; python_version >= "3.11" and python_version < "4.0"
          - lazy-object-proxy==1.9.0 ; python_version >= "3.11" and python_version < "4.0"
          - loguru==0.6.0 ; python_version >= "3.11" and python_version < "4.0"
          - markdown-it-py==3.0.0 ; python_version >= "3.11" and python_version < "4.0"
          - markupsafe==2.1.3 ; python_version >= "3.11" and python_version < "4.0"
          - marshmallow==3.20.1 ; python_version >= "3.11" and python_version < "4.0"
          - mccabe==0.7.0 ; python_version >= "3.11" and python_version < "4.0"
          - mdurl==0.1.2 ; python_version >= "3.11" and python_version < "4.0"
          - mypy-extensions==1.0.0 ; python_version >= "3.11" and python_version < "4.0"
          - mypy==1.5.1 ; python_version >= "3.11" and python_version < "4.0"
          - nodeenv==1.8.0 ; python_version >= "3.11" and python_version < "4.0"
          - numpy==1.25.2 ; python_version >= "3.11" and python_version < "4.0"
          - packaging==23.0 ; python_version >= "3.11" and python_version < "4.0"
          - pandas==1.5.3 ; python_version >= "3.11" and python_version < "4.0"
          - pathspec==0.11.2 ; python_version >= "3.11" and python_version < "4.0"
          - pbr==5.11.1 ; python_version >= "3.11" and python_version < "4.0"
          - pep8-naming==0.12.1 ; python_version >= "3.11" and python_version < "4.0"
          - platformdirs==3.10.0 ; python_version >= "3.11" and python_version < "4.0"
          - pluggy==1.3.0 ; python_version >= "3.11" and python_version < "4.0"
          - pre-commit==3.3.3 ; python_version >= "3.11" and python_version < "4.0"
          - pycodestyle==2.11.0 ; python_version >= "3.11" and python_version < "4.0"
          - pydantic==1.10.12 ; python_version >= "3.11" and python_version < "4.0"
          - pyflakes==3.1.0 ; python_version >= "3.11" and python_version < "4.0"
          - pygments==2.16.1 ; python_version >= "3.11" and python_version < "4.0"
          - pylint==2.17.5 ; python_version >= "3.11" and python_version < "4.0"
          - pytest==7.4.0 ; python_version >= "3.11" and python_version < "4.0"
          - python-dateutil==2.8.2 ; python_version >= "3.11" and python_version < "4.0"
          - python-dotenv==0.21.1 ; python_version >= "3.11" and python_version < "4.0"
          - pytz==2023.3 ; python_version >= "3.11" and python_version < "4.0"
          - pyyaml==6.0.1 ; python_version >= "3.11" and python_version < "4.0"
          - requests==2.31.0 ; python_version >= "3.11" and python_version < "4.0"
          - rich==13.5.2 ; python_version >= "3.11" and python_version < "4.0"
          - ruamel-yaml-clib==0.2.7 ; platform_python_implementation == "CPython" and python_version < "3.12" and python_version >= "3.11"
          - ruamel-yaml==0.17.32 ; python_version >= "3.11" and python_version < "4.0"
          - ruff==0.0.286 ; python_version >= "3.11" and python_version < "4.0"
          - safety==2.4.0b1 ; python_version >= "3.11" and python_version < "4.0"
          - setuptools==68.1.2 ; python_version >= "3.11" and python_version < "4.0"
          - six==1.16.0 ; python_version >= "3.11" and python_version < "4.0"
          - smmap==5.0.0 ; python_version >= "3.11" and python_version < "4.0"
          - stevedore==5.1.0 ; python_version >= "3.11" and python_version < "4.0"
          - tomlkit==0.12.1 ; python_version >= "3.11" and python_version < "4.0"
          - typing-extensions==4.7.1 ; python_version >= "3.11" and python_version < "4.0"
          - urllib3==2.0.4 ; python_version >= "3.11" and python_version < "4.0"
          - virtualenv==20.24.4 ; python_version >= "3.11" and python_version < "4.0"
          - win32-setctime==1.1.0 ; python_version >= "3.11" and python_version < "4.0" and sys_platform == "win32"
          - wrapt==1.15.0 ; python_version >= "3.11" and python_version < "4.0"
