default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "1.1.0"
    hooks:
      - id: sync_with_poetry

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.3.2"
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        args:
          - "--recursive"
          - "--aggregate=vuln"
          - "--configfile=pyproject.toml"
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: src/fight/example
        exclude_types:
          - markdown
      - id: check-added-large-files
        args:
          - "--maxkb=1024"
      - id: check-yaml
        exclude: \.gitlab-ci.yml
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.6.1"
    hooks:
      - id: mypy
        args:
          - "--config-file=pyproject.toml"
          - "--install-types"
          - "--non-interactive"
        additional_dependencies:
          - aiosqlite==0.19.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - annotated-types==0.6.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - anyio==3.7.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - astroid==3.0.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - autoflake==2.2.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - bandit==1.7.5 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - bcrypt==4.0.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - black==23.10.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - certifi==2023.7.22 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - cffi==1.16.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - cfgv==3.4.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - charset-normalizer==3.3.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - click==8.1.7 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - colorama==0.4.6 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0" and (sys_platform == "win32" or platform_system == "Windows")
          - cryptography==41.0.5 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - dill==0.3.7 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - distlib==0.3.7 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - dnspython==2.4.2 ; python_full_version >= "3.11.5" and python_version < "4.0"
          - dparse==0.6.3 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - ecdsa==0.18.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - email-validator==2.0.0.post2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - fastapi-users-db-sqlalchemy==6.0.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - fastapi-users==12.1.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - fastapi-users[sqlalchemy]==12.1.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - fastapi==0.104.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - fastapi[all]==0.104.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - filelock==3.13.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - gitdb==4.0.11 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - gitpython==3.1.40 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - greenlet==3.0.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - h11==0.14.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - httpcore==0.18.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - httptools==0.6.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - httpx==0.25.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - identify==2.5.30 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - idna==3.4 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - iniconfig==2.0.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - isort==5.12.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - itsdangerous==2.1.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - jinja2==3.1.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - loguru==0.7.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - makefun==1.15.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - markdown-it-py==3.0.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - markupsafe==2.1.3 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - marshmallow==3.20.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - mccabe==0.7.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - mdurl==0.1.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - mypy-extensions==1.0.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - mypy==1.6.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - nodeenv==1.8.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - orjson==3.9.10 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - packaging==23.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - passlib[bcrypt]==1.7.4 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pathspec==0.11.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pbr==5.11.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - platformdirs==3.11.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pluggy==1.3.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pre-commit==3.5.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pyasn1==0.5.0 ; python_full_version >= "3.11.5" and python_version < "4"
          - pycparser==2.21 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pydantic-core==2.10.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pydantic-extra-types==2.1.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pydantic-settings==2.0.3 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pydantic==2.4.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pyflakes==3.1.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pygments==2.16.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pyjwt[crypto]==2.8.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pylint==3.0.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pytest-asyncio==0.21.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pytest==7.4.3 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - python-dotenv==1.0.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - python-jose[cryptography]==3.3.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - python-multipart==0.0.6 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - pyyaml==6.0.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - requests==2.31.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - rich==13.6.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - rsa==4.9 ; python_full_version >= "3.11.5" and python_version < "4"
          - ruamel-yaml-clib==0.2.8 ; platform_python_implementation == "CPython" and python_version < "3.13" and python_full_version >= "3.11.5"
          - ruamel-yaml==0.18.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - ruff==0.1.3 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - safety==2.4.0b1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - setuptools==68.2.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - six==1.16.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - smmap==5.0.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - sniffio==1.3.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - sqlalchemy==2.0.22 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - sqlalchemy[asyncio]==2.0.22 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - starlette==0.27.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - stevedore==5.1.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - tomlkit==0.12.1 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - typing-extensions==4.8.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - ujson==5.8.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - urllib3==2.0.7 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - uvicorn[standard]==0.23.2 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - uvloop==0.19.0 ; (sys_platform != "win32" and sys_platform != "cygwin") and platform_python_implementation != "PyPy" and python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - virtualenv==20.24.6 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - watchfiles==0.21.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - websockets==12.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0"
          - win32-setctime==1.1.0 ; python_full_version >= "3.11.5" and python_full_version < "4.0.0" and sys_platform == "win32"
