version: "3.7"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "rest"
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./API_logs.log:/API_logs.log:rw
      - ./restfull.db:/restfull.db:rw
